### ISSUE TITLE
Race condition on the pipe example to write body into request

### ISSUE THREAD

**Issue by igorsechyn** [zupzup/golang-io-pipe#1]
I was using io.pipe package to write body into request as described in http_json.go example. After writing a test and running it with -race flag, it was failing with an error 
> io: read/write on closed pipe

I assume this has to do with the way deferred functions are executed and evaluated. The error was fixed by actually passing the pipeWriter into the anonymous function
`

	pr, pw := io.Pipe()

	go func(pw *io.PipeWriter) {
		// close the writer, so the reader knows there's no more data
		defer pw.Close()

		// write json data into the pipereader through the pipewriter
		if err := json.NewEncoder(pw).Encode(&PayLoad{Content: "Hello Pipe!"}); err != nil {
			log.Fatal(err)
		}
	}(pw)
`

**Comment by zupzup** [comment]
Hi,

Thanks - nice catch! I didn't run it with -race when I created the examples, but I'll definitely next time :)

I fixed it in the example.
